language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install

script: ./vendor/bin/phpunit
